name: Build Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Apps
        run: ./gradlew mobile:assembleDebug wear:assembleDebug
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload Files (Mobile)
        run: aws s3 cp mobile/build/outputs/apk/debug/mobile-debug.apk s3://${{ secrets.S3_BUCKET }}
      - name: Upload Files (Wear)
        run: aws s3 cp wear/build/outputs/apk/debug/wear-debug.apk s3://${{ secrets.S3_BUCKET }}