name: Build Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build App for Mobile
        run: ./gradlew mobile:assembleDebug
      - name: Build App for Wear
        run: ./gradlew wear:assembleDebug
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Apps
          path: |
            mobile/build/outputs/apk/debug/mobile-debug.apk
            wear/build/outputs/apk/debug/wear-debug.apk